### 
# -------------------------------------
# CADASTRAR DADO
POST {{host}}/editor
Content-Type: application/json

{
    "cod": "1",
    "comando": "comando1",
    "contexto": "...",
    "processamento": "...",
    "narrativa": "...",
    "saida": "..."
}

### 
#------------------------------------
# 01 --> MOSTRAR TODOS DADOS --fazer esta rota
GET {{host}}/editor
Content-Type: application/json

### 
#------------------------------------